### PR TITLE
Type and glob support

### PR DESCRIPTION
**Pull request by kasimebrahim**
as per https://github.com/singnet/miner/issues/12 and https://github.com/singnet/miner/issues/13
Contains Type-checking, Glob support and Benchmark.

### CODE REVIEW

**Comment by kasimebrahim** [comment]
Oh needs https://github.com/singnet/ure/pull/27

**Comment by ngeiswei** [comment]
@kasimebrahim, the unit tests fail, it is because https://github.com/singnet/ure/pull/27 is incomplete as you mentioned here https://github.com/singnet/ure/pull/27#issuecomment-724590248?

**Comment by kasimebrahim** [comment]
The remaining issue in singnet/ure#27 shouldn't fail the unit test. It is because of https://github.com/opencog/atomspace/pull/2776 we need those changes in the singnet atomspace.

**Comment by ngeiswei** [comment]
Thanks a lot for your contribution @kasimebrahim

**Pull request merged**
